<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ShuffleSeries.Shared.Core\ShuffleSeries.Shared.Core.Application\ShuffleSeries.Shared.Core.Application.csproj" />
      <ProjectReference Include="..\ShuffleSeries.Identity.Domain\ShuffleSeries.Identity.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ShuffleSeries.Identity.Tests" />
        <InternalsVisibleTo Include="ShuffleSeries.Identity.IntegrationTests" />
    </ItemGroup>

</Project>
