<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="7.3.1" />
        <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShuffleSeries.Shared.Core\ShuffleSeries.Shared.Core.Web\ShuffleSeries.Shared.Core.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
