@ShuffleSeries.Microservices.ApiGateway_HostAddress = http://localhost:5001

### 1. API Gateway Kendi Sağlığı (Liveness Probe)
GET {{ShuffleSeries.Microservices.ApiGateway_HostAddress}}/health/live
Accept: application/json

### 2. API Gateway Kendi Sağlığı (Readiness Probe)
GET {{ShuffleSeries.Microservices.ApiGateway_HostAddress}}/health/ready
Accept: application/json

### 3. Catalog Mikroservisi Sağlığı (Gateway YARP Üzerinden - Liveness)
GET {{ShuffleSeries.Microservices.ApiGateway_HostAddress}}/catalog-api/health/live
Accept: application/json

### 4. Catalog Mikroservisi Sağlığı (Gateway YARP Üzerinden - Readiness)
GET {{ShuffleSeries.Microservices.ApiGateway_HostAddress}}/catalog-api/health/ready
Accept: application/json

###

