<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ShuffleSeries.Catalog.Tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit" Version="8.3.7" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
      <PackageReference Include="Quartz" Version="3.19.1" />
      <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.19.1" />
      <PackageReference Include="Quartz.Extensions.Hosting" Version="3.19.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ShuffleSeries.Shared.Core\ShuffleSeries.Shared.Core.Infrastructure\ShuffleSeries.Shared.Core.Infrastructure.csproj" />
      <ProjectReference Include="..\ShuffleSeries.Catalog.Domain\ShuffleSeries.Catalog.Domain.csproj" />
    </ItemGroup>

</Project>
